name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Firebase

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project nicketvip
        env:
          FIREBASE_SERVICE_ACCOUNT_NICKETVIP: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICKETVIP }}
